name: get_data
on:
  workflow_dispatch:
jobs:
  build-jvm:
    runs-on: ubuntu-latest
    env:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
      - run: oc get pods
      - name: Get  image streams
        run: oc get is
